Create database DuAnTotNghiep;
use DuAnTotNghiep;

CREATE TABLE [ACCOUNT] (
	[USERNAME] [nvarchar](50) NOT NULL PRIMARY KEY,
	[PASSWORD] [varchar](max) NOT NULL,
	[PHONE] [nvarchar](12) NULL,
	[GENDER] [bit] NOT NULL,
	[PHOTO] [nvarchar](max) NULL,
	[FULLNAME] [nvarchar](max) NULL,
	[EMAIL] [nvarchar](max) NULL,
)

CREATE TABLE [ROLE](
	[ROLEID] [nvarchar](10) NOT NULL PRIMARY KEY,
	[ROLENAME] [nvarchar](max) NOT NULL
)

CREATE TABLE [ROLEACC](
	[ROLEACCID] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[USERNAME] [nvarchar](50) NOT NULL,
	[ROLEID] [nvarchar](10) NOT NULL,
	FOREIGN KEY ([USERNAME]) REFERENCES [ACCOUNT]([USERNAME]),
	FOREIGN KEY ([ROLEID]) REFERENCES [ROLE]([ROLEID])
)

CREATE TABLE [CATEGORY](
	[CATEID] [nvarchar](10) NOT NULL PRIMARY KEY,
	[CATENAME] [nvarchar](max) NOT NULL
)


CREATE TABLE [PRODUCT](
	[PRODUCTID] [bigint] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[PRODUCTNAME] [nvarchar](max) NOT NULL,
	[PRICE] [float] NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[CATEID] [nvarchar](10) NOT NULL,
	[IMAGE] [nvarchar](max) NOT NULL,
	[DATECREATE] [datetime] NOT NULL,
	[AUTHOR] [nvarchar](max),
	FOREIGN KEY ([CATEID]) REFERENCES [CATEGORY]([CATEID])
)

CREATE TABLE [CART](
	[CARTID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[USERNAME] [nvarchar](50) NULL,
	[PRODUCTID] [bigint] NULL,
	[QUANTITY] [int] NULL,
	[SUMPRICE] [float] NULL,
	FOREIGN KEY ([USERNAME]) REFERENCES [ACCOUNT]([USERNAME]),
	FOREIGN KEY ([PRODUCTID]) REFERENCES [PRODUCT]([PRODUCTID])
)

CREATE TABLE [BILL](
	[BILLID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[BILLDATE] [date] NULL,
	[STATUS] [int] NULL,
	[ADDRESS] [NVARCHAR](MAX) NULL,
	[USERNAME] [nvarchar](50) NULL,
	[PAYMENTMT] [int] NULL,
	[SHIPFEE] [float] NULL,
	[SUMPRICE] [float] NULL,
	FOREIGN KEY ([USERNAME]) REFERENCES [ACCOUNT]([USERNAME])
)

CREATE TABLE [BILLDETAILS](
	[BILLDETAILID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[SUMPRICE] [float] NOT NULL,
	[BILLID] [int] NULL,
	[QUANTITY] [int] NULL,
	[PRODUCTID] [bigint] NULL
	FOREIGN KEY ([PRODUCTID]) REFERENCES [PRODUCT]([PRODUCTID]),
	FOREIGN KEY ([BILLID]) REFERENCES [BILL]([BILLID]),
)

CREATE TABLE [FAVORITE](
	[FAVID] [bigint] IDENTITY(1,1) NOT NULL,
	[FAVDATE] [date] NOT NULL,
	[PRODUCTID] [bigint] NOT NULL,
	[USERNAME] [nvarchar](50) NOT NULL,
	FOREIGN KEY ([USERNAME]) REFERENCES [ACCOUNT]([USERNAME]),
	FOREIGN KEY ([PRODUCTID]) REFERENCES [PRODUCT]([PRODUCTID])
)


ALTER TABLE [PRODUCT]
ADD [DESCRIPTION] NVARCHAR(MAX);